string="Hey everyone!"

print("Capitalize       :",string.capitalize())
print("casefold         :",string.casefold())
print("count            :",string.count("e"))
print("encode           :",string.encode())
print("endswith         :",string.endswith("e"))
print("expandtabs       :",string.expandtabs())
print("find             :",string.find("!"))
print("format           :",string.format("e"))
print("index            :",string.index("y"))
print("isalnum          :",string.isalnum())
print("isascii          :",string.isascii())
print("islower          :",string.islower())
print("istitle          :",string.istitle())
print("join             :",string.join(" 5"))
print("replace          :",string.replace(" Whts up!"," "))
print("split            :",string.split("O"))
print("title            :",string.title())